name: GitHub Actions
run-name: Running necessary checks 🚀
on: [push]
jobs:
  Code-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: 🚚 Installing dependencies
        run: yarn 
      - name: 🏷️ running typecheck
        run: yarn build
      - name: 🧪 Running tests
        run: yarn test
      - name: 🚨 Linting code
        run: yarn lint
      - name: 🚨 prettier check code
        run: yarn format:check
